config/routes.rb
Rails.application.routes.draw do

  resources :testimonials
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

  get '/howitworks' => 'home#howitworks'
  get '/contact' => 'home#contact'
  get '/subjects' => 'home#subjects'
  get '/about' => 'home#about'
  get '/testimonials' => 'home#testimonials'
  get '/signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController



end

app/views/home/about.html.erb
<div id="about">
<h2>A little bit about me:</h2>
<hr>


<%= image_tag 'portrait.jpg', id: 'portrait' %>
<p>Hi ya’ll!</p>
<p>My name is Stephen, and I was born and raised in Dallas, TX. I attended Highland Park schools for the entirety of my youth, maintaining an immense interest in both academics and athletics. <%= image_tag 'hp-logo.png', :id => 'hp' %>
  I constantly strove to expand my intellectual curiosity, participating in the most challenging and difficult courses I could sign up for, and ended up with over 20 AP courses completed prior to college.

  If I was not studying at home, I was out at the athletic fields, participating in football, lacrosse, and cross-country. During my tenure at HP, I was member of 2 state champion lacrosse teams and 1 state finalist cross-county team.</p>
<br>
<p>I graduated Summa Cum Laude from Highland Park High School in 2011, and went on to attend the University of Virginia. At UVA, I pursued a degree in biomedical engineering, focusing on medical device development.
 <%= image_tag 'uva-logo.png', :id => 'uva' %>
  During my free time, I constantly hiked in Shenandoah National Park on the Appalachian trail and even made it out to the Outer Banks occasionally to surf. I graduated with high distinction in the spring of 2015. I am now back in Dallas, currently applying to medical schools. I submitted applications in the Fall, and have been interviewing ever since, planning to matriculate at a medical school in August 2016, though I have yet to make a final decision as to where. </p>
  <%= image_tag 'cross-country.jpg', id: 'cc' %>
<br>
<p><strong><span style="text-decoration: underline">More about my teaching experience:</span></strong></p>
<br>

<p>Since I was a sophomore in high school, I have tutored fellow students, and continued to do so at UVA. In 2007, my brother and I created Highland Park Tutors, a company that employed high school students to tutor fellow students. The company ran well for several years, but eventually disbanded due to both of us being away at college, and the subsequent lack of good management.</p>
<br>

<p>In the summer of 2014, I taught an MCAT preparatory course for Examkrackers, Inc., instructing a group of 20 students in physics and chemistry.In the fall of 2014, I was selected to be a teaching fellow for a high level engineering course at UVA, where I co-instructed a class of over 70 students in the subject of bioelectricity. Teaching remains one of my highest passions, as I draw immense satisfaction from translating complex concepts into more digestible pieces of information so that I may improve a students’ understanding. I look forward to helping your son or daughter excel in their classes!</p>


</div>

app/views/home/contact.html.erb
<div id="contact">
  <h2>My Contact Info:</h2>
  <hr>

  <br>
  <br>

  <p>Email: <a href="mailto:sgr2ak@virginia.edu">sgr2ak@virginia.edu</a></p>
  <br>
  <p>Cell: 214.686.7245</p>
</div>

app/views/home/howitworks.html.erb
<div id="howitworks">
    <h2>How it Works:</h2>
    <hr>
    <ul>
      <li>Log in or sign up.</li>
      <li>Click "book a session", which will take you to your Google calendar. (You may need a Gmail account to book online.)</li>
      <li>Pick a time slot.</li>
      <li>If it's last minute, just call or text me @ 214.686.7245.</li>
      <li>I come to your home.</li>
      <li>We study hard. ;)</li>
      <br>
      <hr>
      <li>Sessions are 55 minutes long.</li>
      <li>There is a $20 fee for cancellations or rescheduling of sessions within 12 hours of the originally booked session.</li>
      <li>My schedule is subject to change.</li>
    </ul>
  </div>

app/views/home/index.html.erb
<div class="register-wrap">
<% if !signed_in? %>
<div class="register-buttons">
      <%= link_to "Log In", signin_path, id: 'login' %>
      <%= link_to "Sign Up", signup_path, id: 'signup' %>
</div>
<% end %>
</div>

app/views/home/subjects.html.erb
<div class="subjects">
  <h2>What I can help you with:</h2>
  <hr>
  <h3>High School Classes:</h3>
  <h3>(including pre-AP & AP)</h3>
  <hr>
  <ul>
    <li>Physics</li>
    <li>Biology I & II</li>
    <li>Chemistry I & II</li>
    <li>Spanish I-III</li>
    <li>Geometry</li>
    <li>Algebra I & II</li>
    <li>Pre-Calculus</li>
    <li>Calculus</li>
    <li>Computer Science I</li>
  </ul>
</div>

<div class="subjects">
  <h3>Up to 8<sup>th</sup> grade:</h3>
  <hr>
  <ul>
    <li>Math</li>
    <li>Science</li>
    <li>Spanish</li>
  </ul>
</div>