config/routes.rb
Rails.application.routes.draw do

  resources :testimonials
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

  get '/howitworks' => 'home#howitworks'
  get '/contact' => 'home#contact'
  get '/subjects' => 'home#subjects'
  get '/about' => 'home#about'
  get '/testimonials' => 'home#testimonials'
  get '/signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  validates :feedback, presence: true

  # ratyrate_rateable 'overall'
  # ratyrate_rater

end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController

  include SessionsHelper
  # before_action :set_testimonial, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: :destroy
  # before_action :signed_in_user, only: [:index, :new, :create]

  def index
    @testimonials = Testimonial.all
    @user = current_user
  end

  def show
    @testimonial = Testimonial.find(params[:id])
  end

  def new
    @testimonial = Testimonial.new
  end

  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to testimonials_url, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to @testimonial, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    Testimonial.find(params[:id]).destroy
    flash[:success] = "Review deleted"
    redirect_to testimonials_url
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    def testimonial_params
      params.require(:testimonial).permit(:feedback, :name)
    end

end

app/views/testimonials/edit.html.erb
<h1>Editing Testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<div id="reviews">
  <p id="notice"><%= notice %></p>

  <h2>Reviews</h2>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @testimonials.each do |testimonial| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
          <td><%= testimonial.feedback %></td>
          <td class="name"><%= testimonial.name %></td>

              <td></td>



        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'Add Feedback!', new_testimonial_path, class: "button" %>
<br>
<br>
<p><%= link_to "Back", current_user || root_url %></p>

app/views/testimonials/new.html.erb
<h1>New Review</h1>

<%= form_for(@testimonial) do |f| %>

  <div class="form-group">
    <%= f.text_area :feedback, rows: 10, cols: 50, :placeholder => "Feedback...." %><br>
  </div>
  <div class="form-group">
    <%= f.text_field :name, :placeholder => "Name (optional)" %><br>
  </div>
    <%= f.submit 'Submit' %>
<% end %>

<br>
<p><%= link_to 'Back', testimonials_path %></p>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>