config/routes.rb
Rails.application.routes.draw do

  resources :testimonials
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

  get '/howitworks' => 'home#howitworks'
  get '/contact' => 'home#contact'
  get '/subjects' => 'home#subjects'
  get '/about' => 'home#about'
  get '/testimonials' => 'home#testimonials'
  get '/signup' => 'users#new'
  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Stephen's Tutoring" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>

<body>
  <div id="wrap">
    <div class="wrapper">
      <div id="header">
        <%= image_tag ('logo.png'), id: 'logo' %>
        <div id="title">Stephen Ramon's Tutoring Services</div>
        <div id="subtitle">for students in Park Cities and surrounding areas</div>
      </div>
    </div>
 <!--  Left navbar -->
    <div id="navbar">
      <ul>
        <li><%= link_to "Home", root_path %>
        <li><%= link_to "How it Works", howitworks_path %>
        <li><%= link_to "Contact", contact_path %>
        <li><%= link_to "Subjects", subjects_path %>
        <li><%= link_to "About Me", about_path %>
        <li><%= link_to "Reviews", testimonials_path %>
      </ul>
    </div>
<!-- Right navbar -->
    <% if signed_in? %>
      <div id="r-navbar">
        <ul>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li><%= link_to "My Profile", user_path(current_user) %></li>
          <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
        </ul>
      </div>
    <% end %>


  <div id="content">

      <%= yield %>
  </div>
</div>
        <!-- <div class="push"></div> -->
    <div id="footer">
      <p>Created by <a href="http://www.marisaramon.com">Marisa Ramon</a>, 2016.</p>
    </div>

  <!-- </div> -->
</body>
</html>